// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechnoStore.Infrastructure.Data;

#nullable disable

namespace TechnoStore.Infrastructure.Migrations
{
    [DbContext(typeof(TechnoStoreDbContext))]
    partial class TechnoStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechnoStore.Domain.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("TechnoStore.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Điện thoại thông minh các hãng",
                            IsActive = true,
                            Name = "Smartphone"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Máy tính xách tay các hãng",
                            IsActive = true,
                            Name = "Laptop"
                        });
                });

            modelBuilder.Entity("TechnoStore.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderCode")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TechnoStore.Domain.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("TechnoStore.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Samsung",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Màn hình 6.7 inch Super AMOLED, RAM 8GB, ROM 128GB, Pin 5000mAh. Smartphone phân khúc giá rẻ với thiết kế hiện đại.",
                            ImageUrl = "/images/products/samsung-galaxy-a16.jpg",
                            IsActive = true,
                            Name = "Samsung Galaxy A16",
                            Price = 4490000m,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Samsung",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Màn hình 6.7 inch Dynamic AMOLED 2X, Exynos 2400e, RAM 8GB, ROM 256GB. Flagship phân khúc trung bình.",
                            ImageUrl = "/images/products/samsung-galaxy-s24-fe.jpg",
                            IsActive = true,
                            Name = "Samsung Galaxy S24 FE",
                            Price = 12990000m,
                            StockQuantity = 30,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Samsung",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Màn hình 6.9 inch Dynamic AMOLED 2X, Snapdragon 8 Elite, RAM 12GB, ROM 512GB, Camera 200MP. Flagship cao cấp nhất.",
                            ImageUrl = "/images/products/samsung-galaxy-s25-ultra.jpg",
                            IsActive = true,
                            Name = "Samsung Galaxy S25 Ultra",
                            Price = 33990000m,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Apple",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Màn hình 6.1 inch Super Retina XDR, Chip A16 Bionic, RAM 6GB, ROM 128GB. iPhone thế hệ mới với Dynamic Island.",
                            ImageUrl = "/images/products/iphone-15.jpg",
                            IsActive = true,
                            Name = "iPhone 15",
                            Price = 15990000m,
                            StockQuantity = 40,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Apple",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Màn hình 6.1 inch Super Retina XDR, Chip A18, RAM 8GB, ROM 256GB. Hỗ trợ Apple Intelligence.",
                            ImageUrl = "/images/products/iphone-16.jpg",
                            IsActive = true,
                            Name = "iPhone 16",
                            Price = 22490000m,
                            StockQuantity = 35,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Apple",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Màn hình 6.9 inch Super Retina XDR, Chip A18 Pro, RAM 8GB, ROM 512GB, Camera 48MP 5x Zoom. Flagship đỉnh cao.",
                            ImageUrl = "/images/products/iphone-16-pro-max.jpg",
                            IsActive = true,
                            Name = "iPhone 16 Pro Max",
                            Price = 34490000m,
                            StockQuantity = 25,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Xiaomi",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Màn hình 6.67 inch AMOLED 120Hz, Dimensity 7025 Ultra, RAM 8GB, ROM 128GB. Smartphone giá rẻ hiệu năng cao.",
                            ImageUrl = "/images/products/redmi-note-14.jpg",
                            IsActive = true,
                            Name = "Redmi Note 14",
                            Price = 4990000m,
                            StockQuantity = 60,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Xiaomi",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Màn hình 6.36 inch LTPO AMOLED, Snapdragon 8 Elite, RAM 12GB, ROM 256GB. Flagship nhỏ gọn mạnh mẽ.",
                            ImageUrl = "/images/products/xiaomi-15.jpg",
                            IsActive = true,
                            Name = "Xiaomi 15",
                            Price = 12990000m,
                            StockQuantity = 25,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Xiaomi",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Màn hình 6.73 inch LTPO AMOLED, Snapdragon 8 Elite, RAM 16GB, ROM 512GB, Camera Leica 50MP. Ultra flagship.",
                            ImageUrl = "/images/products/xiaomi-15-ultra.jpg",
                            IsActive = true,
                            Name = "Xiaomi 15 Ultra",
                            Price = 22990000m,
                            StockQuantity = 15,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            Brand = "OPPO",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Màn hình 6.67 inch HD+, Snapdragon 6s Gen 1, RAM 6GB, ROM 128GB. Smartphone giá rẻ pin trâu.",
                            ImageUrl = "/images/products/oppo-a3.jpg",
                            IsActive = true,
                            Name = "OPPO A3",
                            Price = 4290000m,
                            StockQuantity = 55,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            Brand = "OPPO",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Màn hình 6.59 inch AMOLED 120Hz, Dimensity 8350, RAM 12GB, ROM 256GB. Thiết kế thời trang, camera AI.",
                            ImageUrl = "/images/products/oppo-reno-13.jpg",
                            IsActive = true,
                            Name = "OPPO Reno 13",
                            Price = 9990000m,
                            StockQuantity = 30,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            Brand = "OPPO",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Màn hình 6.59 inch LTPO AMOLED, Dimensity 9400, RAM 16GB, ROM 512GB, Camera Hasselblad. Flagship photography.",
                            ImageUrl = "/images/products/oppo-find-x8.jpg",
                            IsActive = true,
                            Name = "OPPO Find X8",
                            Price = 19990000m,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            Brand = "ASUS",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Màn hình 15.6 inch FHD, Intel Core i5-1235U, RAM 8GB, SSD 512GB. Laptop văn phòng mỏng nhẹ.",
                            ImageUrl = "/images/products/asus-vivobook-15.jpg",
                            IsActive = true,
                            Name = "ASUS VivoBook 15",
                            Price = 11990000m,
                            StockQuantity = 25,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            Brand = "ASUS",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Màn hình 15.6 inch FHD 144Hz, Intel Core i7-12700H, RTX 4060, RAM 16GB, SSD 512GB. Laptop gaming bền bỉ.",
                            ImageUrl = "/images/products/asus-tuf-gaming-f15.jpg",
                            IsActive = true,
                            Name = "ASUS TUF Gaming F15",
                            Price = 21990000m,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            Brand = "ASUS",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Màn hình 16 inch QHD 240Hz, Intel Core i9-14900HX, RTX 4070, RAM 32GB, SSD 1TB. Gaming laptop cao cấp.",
                            ImageUrl = "/images/products/asus-rog-strix-g16.jpg",
                            IsActive = true,
                            Name = "ASUS ROG Strix G16",
                            Price = 39990000m,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Dell",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Màn hình 15.6 inch FHD, Intel Core i5-1335U, RAM 8GB, SSD 256GB. Laptop phổ thông đáng tin cậy.",
                            ImageUrl = "/images/products/dell-inspiron-15.jpg",
                            IsActive = true,
                            Name = "Dell Inspiron 15",
                            Price = 12990000m,
                            StockQuantity = 30,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Dell",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Màn hình 15.6 inch FHD, Intel Core i7-1365U, RAM 16GB, SSD 512GB. Laptop doanh nhân bảo mật cao.",
                            ImageUrl = "/images/products/dell-latitude-5540.jpg",
                            IsActive = true,
                            Name = "Dell Latitude 5540",
                            Price = 24990000m,
                            StockQuantity = 15,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Dell",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Màn hình 16 inch OLED 3.2K, Intel Core Ultra 9, RTX 4070, RAM 32GB, SSD 1TB. Ultrabook cao cấp nhất.",
                            ImageUrl = "/images/products/dell-xps-16.jpg",
                            IsActive = true,
                            Name = "Dell XPS 16",
                            Price = 44990000m,
                            StockQuantity = 8,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Lenovo",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Màn hình 15.6 inch FHD, AMD Ryzen 5 7520U, RAM 8GB, SSD 256GB. Laptop sinh viên giá tốt.",
                            ImageUrl = "/images/products/lenovo-ideapad-3.jpg",
                            IsActive = true,
                            Name = "Lenovo IdeaPad 3",
                            Price = 9990000m,
                            StockQuantity = 35,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Lenovo",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Màn hình 16 inch WUXGA, Intel Core i7-1360P, RAM 16GB, SSD 512GB. Laptop doanh nhân bàn phím tốt nhất.",
                            ImageUrl = "/images/products/lenovo-thinkpad-e16.jpg",
                            IsActive = true,
                            Name = "Lenovo ThinkPad E16",
                            Price = 19990000m,
                            StockQuantity = 18,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 21,
                            Brand = "Lenovo",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Màn hình 16 inch WQXGA 240Hz, AMD Ryzen 9 7945HX, RTX 4070, RAM 32GB, SSD 1TB. Gaming laptop hiệu năng quái vật.",
                            ImageUrl = "/images/products/lenovo-legion-pro-5.jpg",
                            IsActive = true,
                            Name = "Lenovo Legion Pro 5",
                            Price = 41990000m,
                            StockQuantity = 10,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 22,
                            Brand = "HP",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Màn hình 15.6 inch FHD, Intel Core i3-1215U, RAM 8GB, SSD 256GB. Laptop cơ bản cho học tập và văn phòng.",
                            ImageUrl = "/images/products/hp-15.jpg",
                            IsActive = true,
                            Name = "HP 15",
                            Price = 10990000m,
                            StockQuantity = 40,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 23,
                            Brand = "HP",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Màn hình 15.6 inch FHD IPS, Intel Core i7-1355U, RAM 16GB, SSD 512GB. Laptop đa năng thiết kế đẹp.",
                            ImageUrl = "/images/products/hp-pavilion-15.jpg",
                            IsActive = true,
                            Name = "HP Pavilion 15",
                            Price = 17990000m,
                            StockQuantity = 22,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 24,
                            Brand = "HP",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Màn hình 16.1 inch QHD 165Hz, Intel Core i9-13900HX, RTX 4080, RAM 32GB, SSD 1TB. Gaming laptop siêu mạnh.",
                            ImageUrl = "/images/products/hp-omen-16.jpg",
                            IsActive = true,
                            Name = "HP Omen 16",
                            Price = 37990000m,
                            StockQuantity = 12,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TechnoStore.Domain.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("TechnoStore.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Nguyễn Huệ, Q.1, TP.HCM",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@technostore.com",
                            FullName = "Admin TechnoStore",
                            IsActive = true,
                            PasswordHash = "$2a$11$9VpEYrG4lC7PFv5zW.2Ppeq6KpNu0U845V3y8pkQ56LSvNPDMJ7RK",
                            Phone = "0901234567",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Lê Lợi, Q.3, TP.HCM",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer@technostore.com",
                            FullName = "Nguyễn Văn Khách",
                            IsActive = true,
                            PasswordHash = "$2a$11$Y5xsnkdo3Dms5zZcj9z1XeqUSw.qf.yQsY.h.eguIs3Ax4ojQvcVG",
                            Phone = "0912345678",
                            Role = "Customer"
                        });
                });

            modelBuilder.Entity("TechnoStore.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("TechnoStore.Domain.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnoStore.Domain.Entities.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechnoStore.Domain.Entities.Order", b =>
                {
                    b.HasOne("TechnoStore.Domain.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechnoStore.Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("TechnoStore.Domain.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnoStore.Domain.Entities.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TechnoStore.Domain.Entities.Product", b =>
                {
                    b.HasOne("TechnoStore.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TechnoStore.Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("TechnoStore.Domain.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TechnoStore.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TechnoStore.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("TechnoStore.Domain.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductImages");
                });

            modelBuilder.Entity("TechnoStore.Domain.Entities.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
